<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KLqhWK1' shared service.

return $this->privates['.service_locator.KLqhWK1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'episode' => ['privates', '.errored..service_locator.KLqhWK1.App\\Entity\\Episode', NULL, 'Cannot autowire service ".service_locator.KLqhWK1": it references class "App\\Entity\\Episode" but no such service exists.'],
], [
    'episode' => 'App\\Entity\\Episode',
]);
