<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-http/AccessMap.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcher.php';
include_once $this->targetDirs[3].'/vendor/symfony/expression-language/Expression.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/program'), [0 => 'ROLE_SUBSCRIBER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/register'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login$'), [0 => ($this->privates['.security.expression.cKdL19O'] ?? ($this->privates['.security.expression.cKdL19O'] = new \Symfony\Component\ExpressionLanguage\Expression('!is_granted(\'ROLE_USER\')')))], NULL);

return $instance;
