<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.cache_warmer.expression' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-bundle/CacheWarmer/ExpressionCacheWarmer.php';

return $this->privates['security.cache_warmer.expression'] = new \Symfony\Bundle\SecurityBundle\CacheWarmer\ExpressionCacheWarmer(new RewindableGenerator(function () {
    yield 0 => ($this->privates['.security.expression.cKdL19O'] ?? ($this->privates['.security.expression.cKdL19O'] = new \Symfony\Component\ExpressionLanguage\Expression('!is_granted(\'ROLE_USER\')')));
}, 1), ($this->privates['security.expression_language'] ?? $this->load('getSecurity_ExpressionLanguageService.php')));
