<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrZqjZF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrZqjZF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPrZqjZF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPrZqjZF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPrZqjZF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PrZqjZF',
    'container.build_id' => 'b2ebd86a',
    'container.build_time' => 1575896860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrZqjZF');
