<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3p6qx7z\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3p6qx7z/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3p6qx7z.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3p6qx7z\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3p6qx7z\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3p6qx7z',
    'container.build_id' => '90f309d9',
    'container.build_time' => 1575907327,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3p6qx7z');
