<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDE3cqWN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDE3cqWN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDE3cqWN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDE3cqWN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDE3cqWN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DE3cqWN',
    'container.build_id' => '0846f786',
    'container.build_time' => 1575990055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDE3cqWN');
